// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMember(ctx context.Context, id int64) error
	GetMember(ctx context.Context, id int64) (Member, error)
	GetMemberByNumber(ctx context.Context, phoneNumber sql.NullString) (Member, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListMembers(ctx context.Context) ([]Member, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateMemberName(ctx context.Context, arg UpdateMemberNameParams) (Member, error)
}

var _ Querier = (*Queries)(nil)
