name: CI/CD Heatmap App

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  db:
    name: create-db
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:17.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: ccc
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - pgdata:/var/lib/postgresql/data
    steps:
      - name: Set up Go 1.23.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
        id: go

      - name: Check out code into the Go module dir
        uses: actions/checkout@v2

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Make migrations
        run: make migrateup

      - name: Build and run go image
        run: make build && make run
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          DB_SOURCE: ${{ secrets.DATABASE_URL }}
          SENDER_NUMBER: ${{secrets.SENDER_NUMBER}}
          DB_DRIVER: ${{secrets.DB_DRIVER}}
          SERVER_ADDRESS: ${{secrets.SERVER_ADDRESS}}
